In [33]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:90% !important; }</style>"))

import numpy as np
import matplotlib.pyplot as plt
import sympy as sym

from scipy.stats import norm
from scipy.stats import t
from scipy.stats import chi2

# Radioactividad

In [34]:
def Minimos_cuadrados(x,y,n=1):
    l = x.shape[0]
    b = y
    
    A = np.ones((l,n+1))
    
    for i in range(1,n+1):
        A[:,i] = x**i
        
    AT = np.dot(A.T,A)
    bT = np.dot(A.T,b)

    xsol = np.linalg.solve(AT,bT)
    
    return xsol

def GetModel(x,p):
    
    y = 0.
    for i in range(len(p)):
        y += p[i]*x**i
        
    return y

def GetError(x,y,p,n=1):
    
    l = x.shape[0]
    
    A = np.ones((l,n+1))
    
    for i in range(1,n+1):
        A[:,i] = x**i
        
    # Residuos
    R = y - np.dot(A,p)
    
    sigma2 = np.dot(R.T,R)/(len(y)-len(p))
    
    Cov = sigma2*np.linalg.inv(np.dot(A.T,A))
    
    R2 = None
    if np.shape(Cov) == (2,2):
        R2 = (Cov[0][1]**2)/(Cov[0][0]*Cov[1][1])

    return (Cov,R2,R)

def Get_sigma(Cov):
    sigmaai = np.sqrt(np.diagonal(Cov))
    return sigmaai[::-1]

def Error_relativo(X_real,X_exp):
    return (np.abs(X_exp - X_real)/X_real)

def presicion(d,v):
    p = (d/v)
    if p <= 0.1:
        return p,True
    else:
        return p,False
    
def exactitud(xr,xm,d):
    e = (np.abs(xr-xm))
    if e <= (2.5*d):
        return e/d,True
    else:
        return e/d,False
    
def Promedio(lista):
    return np.sum(lista) / len(lista)

def promedios(M):
    P = []
    for i in M:
        P.append(Promedio(i))
    return tuple(P)

def Standard_Deviation(lista):
    return np.sqrt(np.sum((lista-Promedio(lista))**2) / len(lista))

def SDs(M):
    S = []
    for i in M:
        S.append(Standard_Deviation(i))
    return tuple(S)

def conteo(lista):
    L = []
    L.append(lista[0])
    for i in range(len(lista)-1):
        L.append(lista[i+1]-lista[i])
    return np.array(L)

def conteo3(lista):
    n = len(lista)
    L = []
    L.append(lista[2])
    for i in range(2,int(((n-(n%3))/3)+1)):
        L.append(lista[(3*i)-1]-lista[(3*(i-1))-1])
    return np.array(L)

X = sym.Symbol('x',real=True)
Y = sym.Symbol('y',real=True)

# Datos

In [35]:
R_amb = 226/10
Dos = np.array([330., 670., 996., 1294., 1624., 1951., 2271., 2569., 2852., 3173.])
Cuatro = np.array([120., 248., 388., 511., 619., 733., 851., 977., 1086., 1183.])
Ocho = np.array([36., 68., 126., 174., 196., 225., 279., 331., 380., 419.])
B1 = np.array([186., 364., 537., 707., 893.])
B2 = np.array([28., 65., 104., 128., 165.])
B3 = np.array([32., 68., 99., 138., 173.])
t1 = np.array([1., 2., 3., 4., 5., 6., 7., 8., 9., 10.])
t2 = np.array([1., 2., 3., 4., 5.])

# Análisis

1 min

In [36]:
Dos_c = conteo(Dos) - R_amb
Cuatro_c = conteo(Cuatro) - R_amb
Ocho_c = conteo(Ocho) - R_amb
B1_c = conteo(B1) - R_amb
B2_c = conteo(B2) - R_amb
B3_c = conteo(B3) - R_amb
M_1 = np.array([Dos_c,Cuatro_c,Ocho_c])
(Promedio(Dos_c),Promedio(Cuatro_c),Promedio(Ocho_c))

(294.7, 95.7, 19.3)

In [37]:
SD2,SD4,SD8 = SDs(M_1)
(SD2,SD4,SD8)

(17.175855146105533, 11.463420083029323, 11.396929411029975)

In [38]:
frec_Dos_c = Dos_c / 60
frec_Cuatro_c = Cuatro_c / 60
frec_Ocho_c = Ocho_c / 60
frec_B1_c = B1_c / 60
frec_B2_c = B2_c / 60
frec_B3_c = B3_c / 60
M_1 = np.array([frec_Dos_c,frec_Cuatro_c,frec_Ocho_c])
M_1

array([[ 5.12333333,  5.29      ,  5.05666667,  4.59      ,  5.12333333,
         5.07333333,  4.95666667,  4.59      ,  4.34      ,  4.97333333],
       [ 1.62333333,  1.75666667,  1.95666667,  1.67333333,  1.42333333,
         1.52333333,  1.59      ,  1.72333333,  1.44      ,  1.24      ],
       [ 0.22333333,  0.15666667,  0.59      ,  0.42333333, -0.01      ,
         0.10666667,  0.52333333,  0.49      ,  0.44      ,  0.27333333]])

In [39]:
P2,P4,P8 = promedios(M_1)
(P2,P4,P8)

(4.911666666666666, 1.595, 0.32166666666666666)

In [40]:
SD2_f,SD4_f,SD8_f = SDs(M_1)
(SD2_f,SD4_f,SD8_f)

(0.28626425243509224, 0.19105700138382206, 0.1899488235171662)

3 min

In [41]:
Dos_c3 = conteo3(Dos) - (3*R_amb)
Cuatro_c3 = conteo3(Cuatro) - (3*R_amb)
Ocho_c3 = conteo3(Ocho) - (3*R_amb)
M_3 = np.array([Dos_c3,Cuatro_c3,Ocho_c3])
(Promedio(Dos_c3),Promedio(Cuatro_c3),Promedio(Ocho_c3))

(882.8666666666668, 294.2, 58.86666666666665)

In [42]:
SD2_3,SD4_3,SD8_3 = SDs(M_3)
(SD2_3,SD4_3,SD8_3)

(38.90444133457716, 18.672618098881223, 22.866763848189994)

In [43]:
frec_Dos_c3 = (Dos_c3/3) / 60
frec_Cuatro_c3 = (Cuatro_c3/3) / 60
frec_Ocho_c3 = (Ocho_c3/3) / 60
M_3 = np.array([frec_Dos_c3,frec_Cuatro_c3,frec_Ocho_c3])
M_3

array([[5.15666667, 4.92888889, 4.62888889],
       [1.77888889, 1.54      , 1.58444444],
       [0.32333333, 0.17333333, 0.48444444]])

In [44]:
P2_3,P4_3,P8_3 = promedios(M_3)
(P2_3,P4_3,P8_3)

(4.904814814814816, 1.6344444444444444, 0.32703703703703696)

In [45]:
SD2_3_f,SD4_3_f,SD8_3_f = SDs(M_3)
(SD2_3_f,SD4_3_f,SD8_3_f)

(0.21613578519209528, 0.10373676721600691, 0.12703757693438886)

10 min

In [46]:
Dos_c10 = Dos[-1] - (10*R_amb)
Cuatro_c10 = Cuatro[-1] - (10*R_amb)
Ocho_c10 = Ocho[-1] - (10*R_amb)
(Dos_c10,Cuatro_c10,Ocho_c10)

(2947.0, 957.0, 193.0)

In [47]:
frec_Dos_c10 = (Dos_c10/10)/60
frec_Cuatro_c10 = (Cuatro_c10/10)/60
frec_Ocho_c10 = (Ocho_c10/10)/60
(frec_Dos_c10,frec_Cuatro_c10,frec_Ocho_c10)

(4.911666666666666, 1.595, 0.32166666666666666)

Barreras

In [48]:
# B1 = papel
# B2 = aluminio
# B3 = plomo
M_B = np.array([B1_c,B2_c,B3_c])
(B1_c,B2_c,B3_c)

(array([163.4, 155.4, 150.4, 147.4, 163.4]),
 array([ 5.4, 14.4, 16.4,  1.4, 14.4]),
 array([ 9.4, 13.4,  8.4, 16.4, 12.4]))

In [49]:
S_B1,S_B2,S_B3 = SDs(M_B)
(S_B1,S_B2,S_B3)

(6.560487786742691, 5.89915248150105, 2.870540018881465)

In [50]:
M_B = np.array([frec_B1_c,frec_B2_c,frec_B3_c])
P_B1,P_B2,P_B3 = promedios(M_B)
(P_B1,P_B2,P_B3)

(2.6, 0.1733333333333333, 0.19999999999999998)

In [51]:
S_B1_f,S_B2_f,S_B3_f = SDs(M_B)
(S_B1_f,S_B2_f,S_B3_f)

(0.10934146311237829, 0.09831920802501751, 0.04784233364802441)